Class {
	#name : #SindarinScriptBuilderTest,
	#superclass : #TestCase,
	#category : #'Sindarin-Scripts-Tests'
}

{ #category : #tests }
SindarinScriptBuilderTest >> testBuildScript [
]

{ #category : #tests }
SindarinScriptBuilderTest >> testReadFromDisk [
]

{ #category : #tests }
SindarinScriptBuilderTest >> testSaveOnDisk [
]

{ #category : #tests }
SindarinScriptBuilderTest >> testScriptDirectory [
]
