"
A Sindarin test debugger to control debugging during tests
"
Class {
	#name : 'SindarinTestDebugger',
	#superclass : 'Object',
	#category : 'Sindarin-Scripts-Tests-utils',
	#package : 'Sindarin-Scripts-Tests',
	#tag : 'utils'
}

{ #category : 'accessing' }
SindarinTestDebugger >> context [
	^self
]

{ #category : 'actions' }
SindarinTestDebugger >> continue [
	^self
]

{ #category : 'accessing' }
SindarinTestDebugger >> debugSession [

	^ self
]

{ #category : 'accessing' }
SindarinTestDebugger >> node [

	^ self
]

{ #category : 'actions' }
SindarinTestDebugger >> resume [

	^ self
]

{ #category : 'accessing' }
SindarinTestDebugger >> sourceNodeExecuted [ 
	^self
]
