Class {
	#name : 'SindarinCommandBuilderTest',
	#superclass : 'TestCase',
	#category : 'Sindarin-Scripts-Tests-tests',
	#package : 'Sindarin-Scripts-Tests',
	#tag : 'tests'
}

{ #category : 'tests' }
SindarinCommandBuilderTest >> testAnonymousCommand [
]

{ #category : 'tests' }
SindarinCommandBuilderTest >> testBuildCommandFromScript [
]

{ #category : 'tests' }
SindarinCommandBuilderTest >> testNamedCommand [
]
